[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Prevent deep-link 404s by routing requests through Next handler
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
